
#include"../Extension/extension.h"


void test(void){

  script* testInitScipt = init_script();
  assert(testInitScipt->stack.maxLen == STACKLENGHT);
  assert(testInitScipt->stack.indexStack == 0);
  assert(testInitScipt->postScript.data != NULL);
  assert(testInitScipt->postScript.indexPostScript == 0);
  assert(testInitScipt->postScript.maxIndexPostScipt == 10);
  free_script(testInitScipt);

  script* testAddDataPostScipt = init_script();
  init_turtle(testAddDataPostScipt);
  assert(testAddDataPostScipt->postScript.indexPostScript == 0);
  int indexTest = testAddDataPostScipt->postScript.indexPostScript;
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  assert(testAddDataPostScipt->postScript.data[indexTest].colour == 'W');
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_moveto == 10);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_moveto == 11);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_lineto == 12);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_lineto == 13);
  assert(testAddDataPostScipt->postScript.indexPostScript == 1);
  assert(testAddDataPostScipt->postScript.maxIndexPostScipt == 10);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  assert(testAddDataPostScipt->postScript.indexPostScript == 9);
  indexTest = testAddDataPostScipt->postScript.indexPostScript;
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  assert(testAddDataPostScipt->postScript.data[indexTest].colour == 'W');
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_moveto == 10);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_moveto == 11);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_lineto == 12);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_lineto == 13);
  assert(testAddDataPostScipt->postScript.indexPostScript == 10);
  assert(testAddDataPostScipt->postScript.maxIndexPostScipt == 10);
  assert(testAddDataPostScipt->postScript.indexPostScript == 10);
  indexTest = testAddDataPostScipt->postScript.indexPostScript;
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  assert(testAddDataPostScipt->postScript.data[indexTest].colour == 'W');
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_moveto == 10);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_moveto == 11);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_lineto == 12);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_lineto == 13);
  assert(testAddDataPostScipt->postScript.indexPostScript == 11);
  assert(testAddDataPostScipt->postScript.maxIndexPostScipt == 20);
  assert(testAddDataPostScipt->postScript.indexPostScript == 11);
  indexTest = testAddDataPostScipt->postScript.indexPostScript;
  addDataPostScript(testAddDataPostScipt,10,11,12,13);
  assert(testAddDataPostScipt->postScript.data[indexTest].colour == 'W');
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_moveto == 10);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_moveto == 11);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].x_lineto == 12);
  assert((int)testAddDataPostScipt->postScript.data[indexTest].y_lineto == 13);
  assert(testAddDataPostScipt->postScript.indexPostScript == 12);
  assert(testAddDataPostScipt->postScript.maxIndexPostScipt == 20);
  free_script(testAddDataPostScipt);  
  
  script* testPushStrStack = init_script();
  init_VARArray(testPushStrStack);
  char dataStr[TOKENMAXLEN] = "1";
  pushStr(testPushStrStack,dataStr);
  assert((int)testPushStrStack->stack.stackArray[0] == 1);
  assert(testPushStrStack->stack.indexStack == 1);
  strcpy(dataStr,"10");
  pushStr(testPushStrStack,dataStr);
  assert((int)testPushStrStack->stack.stackArray[1] == 10);
  assert(testPushStrStack->stack.indexStack == 2);
  strcpy(dataStr,"$A");
  pushStr(testPushStrStack,dataStr);
  assert((int)testPushStrStack->stack.stackArray[2] == 0);
  assert(testPushStrStack->stack.indexStack == 2);
  testPushStrStack->VARArray[0].VARType = NUMBER;
  testPushStrStack->VARArray[0].NUMBER = 10;
  strcpy(dataStr,"$A");
  pushStr(testPushStrStack,dataStr);
  assert((int)testPushStrStack->stack.stackArray[2] == 10);
  assert(testPushStrStack->stack.indexStack == 3);
  free_script(testPushStrStack);

  script* testPushStack = init_script();
  push(testPushStack,10);
  assert((int)testPushStack->stack.stackArray[0] == 10);
  assert(testPushStack->stack.indexStack == 1);
  push(testPushStack,1);
  assert((int)testPushStack->stack.stackArray[1] == 1);
  assert(testPushStack->stack.indexStack == 2);
  free_script(testPushStack);

  script* testPopStack = init_script();
  char dataStrOne[TOKENMAXLEN] = "1";
  pushStr(testPopStack,dataStrOne);
  strcpy(dataStrOne,"2");
  pushStr(testPopStack,dataStrOne);
  strcpy(dataStrOne,"10");
  pushStr(testPopStack,dataStrOne); 
  assert((int)pop(testPopStack) == 10);
  assert((int)pop(testPopStack) == 2);
  assert((int)pop(testPopStack) == 1);
  free_script(testPopStack);

  script* testEvaluatePostFix = init_script();
  char dataStrTwo[TOKENMAXLEN] = "1";
  pushStr(testEvaluatePostFix,dataStrTwo);
  pushStr(testEvaluatePostFix,dataStrTwo);
  evaluatePostfix(testEvaluatePostFix,PLUS);
  assert((int)testEvaluatePostFix->stack.stackArray[0] == 2);
  strcpy(dataStrTwo,"10");
  pushStr(testEvaluatePostFix,dataStrTwo);
  strcpy(dataStrTwo,"1");
  pushStr(testEvaluatePostFix,dataStrTwo);
  evaluatePostfix(testEvaluatePostFix,MINUS);
  assert((int)testEvaluatePostFix->stack.stackArray[1] == 9);
  strcpy(dataStrTwo,"10");
  pushStr(testEvaluatePostFix,dataStrTwo);
  strcpy(dataStrTwo,"1");
  pushStr(testEvaluatePostFix,dataStrTwo);
  evaluatePostfix(testEvaluatePostFix,TIMES);
  assert((int)testEvaluatePostFix->stack.stackArray[2] == 10);
  strcpy(dataStrTwo,"10");
  pushStr(testEvaluatePostFix,dataStrTwo);
  strcpy(dataStrTwo,"2");
  pushStr(testEvaluatePostFix,dataStrTwo);
  evaluatePostfix(testEvaluatePostFix,DIVIDE);
  assert((int)testEvaluatePostFix->stack.stackArray[3] == 5);
  free_script(testEvaluatePostFix);

  script* testSetVar = init_script();
  init_wordArray(testSetVar);
  strcpy(testSetVar->wordArray[0],"A");
  char dataStrThree[TOKENMAXLEN] = "10";
  pushStr(testSetVar,dataStrThree);
  setVAR(testSetVar,0);
  assert(testSetVar->VARArray[0].VARType == NUMBER);
  assert((int)testSetVar->VARArray[0].NUMBER == 10);
  freeWordArray(testSetVar);
  free_script(testSetVar);

  script* testEndElement = init_script();
  init_wordArray(testEndElement);
  strcpy(testEndElement->wordArray[0],"");
  addWord(testEndElement);
  addWord(testEndElement);
  addWord(testEndElement);
  addWord(testEndElement);
  addWord(testEndElement);
  strcpy(testEndElement->wordArray[5],"}");
  testEndElement->index = 0;
  assert(endElement(testEndElement) == 5);
  freeWordArray(testEndElement);
  free_script(testEndElement);

  script* testWordOrNum = init_script();
  init_wordArray(testWordOrNum);
  int varIndex = LTRToVarArrayIndex('A');
  strcpy(testWordOrNum->wordArray[0],"\"RED\"");
  wordOrNum(testWordOrNum,varIndex,0);
  assert(testWordOrNum->VARArray[varIndex].VARType == WORDCOLOUR);
  assert(strcmp(testWordOrNum->VARArray[varIndex].WORDCOLOUR,"\"RED\"")==0);
  strcpy(testWordOrNum->wordArray[0],"10");
  wordOrNum(testWordOrNum,varIndex,0);
  assert(testWordOrNum->VARArray[varIndex].VARType == NUMBER);
  assert((int)testWordOrNum->VARArray[varIndex].NUMBER == 10);
  freeWordArray(testWordOrNum);
  free_script(testWordOrNum);

  script* testIndexGraterThanIndex = init_script();
  init_wordArray(testIndexGraterThanIndex);
  char errorMessage[ERRORMESSAGELENGTH] = "error"; 
  testIndexGraterThanIndex->index = 5;
  assert(MaxIndexGraterThanIndex(testIndexGraterThanIndex,errorMessage)==1);
  assert(strcmp(testIndexGraterThanIndex->errorMessage,errorMessage)==0);
  strcpy(testIndexGraterThanIndex->errorMessage,"");
  testIndexGraterThanIndex->index = 0;
  assert(MaxIndexGraterThanIndex(testIndexGraterThanIndex,errorMessage)==0);
  assert(strcmp(testIndexGraterThanIndex->errorMessage,errorMessage)!=0);
  freeWordArray(testIndexGraterThanIndex);
  free_script(testIndexGraterThanIndex);

  script* testIsWord = init_script();
  init_wordArray(testIsWord);
  testIsWord->outputType = TESTING;
  init_VARArray(testIsWord); 
  strcpy(testIsWord->wordArray[0],"\"BLACK\"");
  isWORD(testIsWord,0,0);
  assert(testIsWord->VARArray[0].VARType == WORDCOLOUR);
  assert(strcmp(testIsWord->VARArray[0].WORDCOLOUR,"\"BLACK\"")==0);
  freeWordArray(testIsWord);
  free_script(testIsWord);

  script* testIsNUM = init_script();
  init_wordArray(testIsNUM);
  testIsNUM->outputType = TESTING;
  init_VARArray(testIsNUM); 
  strcpy(testIsNUM->wordArray[0],"10");
  isNUM(testIsNUM,0,0);
  assert(testIsNUM->VARArray[0].VARType == NUMBER);
  assert((int)testIsNUM->VARArray[0].NUMBER == 10);
  freeWordArray(testIsNUM);
  free_script(testIsNUM);

  script* testInitTokenArray = init_script();
  init_wordArray(testInitTokenArray);
  assert(testInitTokenArray->wordArray != NULL);
  assert(testInitTokenArray->wordArray[0] != NULL);
  freeWordArray(testInitTokenArray);
  free_script(testInitTokenArray);

  script* testAddWord = init_script();
  init_wordArray(testAddWord);
  strcpy(testAddWord->wordArray[0],"wordOne");
  assert(strcmp(testAddWord->wordArray[0],"wordOne")==0);
  addWord(testAddWord);
  strcpy(testAddWord->wordArray[1],"wordTwo");
  assert(strcmp(testAddWord->wordArray[1],"wordTwo")==0);
  addWord(testAddWord);
  strcpy(testAddWord->wordArray[1],"wordThree");
  assert(strcmp(testAddWord->wordArray[1],"wordThree")==0);
  freeWordArray(testAddWord);
  free_script(testAddWord);

  script* testInit_turtle = init_script();
  init_turtle(testInit_turtle);
  assert(testInit_turtle->turtle_Colour == 'W');
  assert(testInit_turtle->turtle_Degrees == 0);
  assert(testInit_turtle->outputType == TESTING);
  freeWordArray(testInit_turtle);
  free_script(testInit_turtle);

  script* testDrawingCordinates = init_script();
  init_turtle(testDrawingCordinates);
  testDrawingCordinates->outputType = TESTING;
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 0;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 0);
  assert(testDrawingCordinates->Y_draw == -10);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 45;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 7);
  assert(testDrawingCordinates->Y_draw == -7);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 90;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 10);
  assert(testDrawingCordinates->Y_draw == 0);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 135;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 7);
  assert(testDrawingCordinates->Y_draw == 7);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 180;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 0);
  assert(testDrawingCordinates->Y_draw == 10);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 225;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == -7);
  assert(testDrawingCordinates->Y_draw == 7);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 270;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == -10);
  assert(testDrawingCordinates->Y_draw == 0);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 315;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == -7);
  assert(testDrawingCordinates->Y_draw == -7);
  testDrawingCordinates->turtle_X = 0;
  testDrawingCordinates->turtle_Y = 0;
  testDrawingCordinates->turtle_Degrees = 360;
  drawingCordinates(testDrawingCordinates, 10);
  assert(testDrawingCordinates->X_draw == 0);
  assert(testDrawingCordinates->Y_draw == -10);
  free_script(testDrawingCordinates);

  script* testDrawLine = init_script(); 
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 0;
  drawLine(testDrawLine, 5);
  testDrawLine->outputType = TESTING;
  Output(testDrawLine);
  assert(testDrawLine->screen[15][25] == 'W');
  assert(testDrawLine->screen[11][25] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 45;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[16][25] == 'W');
  assert(testDrawLine->screen[12][29] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 90;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[16][26] == 'W');
  assert(testDrawLine->screen[16][30] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 135;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[16][25] == 'W');
  assert(testDrawLine->screen[19][28] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 180;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[17][25] == 'W');
  assert(testDrawLine->screen[21][25] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 225;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[16][25] == 'W');
  assert(testDrawLine->screen[20][21] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 270;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[16][24] == 'W');
  assert(testDrawLine->screen[16][20] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 315;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[15][24] == 'W');
  assert(testDrawLine->screen[12][21] == 'W');
  init_turtle(testDrawLine);
  testDrawLine->turtle_Degrees = 360;
  drawLine(testDrawLine, 5);
  assert(testDrawLine->screen[15][25] == 'W');
  assert(testDrawLine->screen[11][25] == 'W');
  free_script(testDrawLine);

  script* testWitchOutput = init_script();
  init_turtle(testWitchOutput);
  char testString[10] = "";
  char *argvTwo = testString;
  witchOutput(testWitchOutput, argvTwo);
  assert(testWitchOutput->outputType==ASCII);
  strcpy(testString,"abcd.txt");
  witchOutput(testWitchOutput, argvTwo);
  assert(testWitchOutput->outputType==TXT);
  strcpy(testString,"abcd.ps");
  witchOutput(testWitchOutput, argvTwo);
  assert(testWitchOutput->outputType==PS);
  strcpy(testString,"abcd.pdf");
  witchOutput(testWitchOutput, argvTwo);
  assert(testWitchOutput->outputType==PDF);
  strcpy(testString,"abcd");
  witchOutput(testWitchOutput, argvTwo);
  assert(testWitchOutput->outputType==ASCII);
  free_script(testWitchOutput);

  script* testOutput = init_script();
  init_turtle(testOutput);
  testOutput->screen[0][0] = 'W';
  testOutput->screen[0][5] = 'W';
  testOutput->screen[0][50] = 'W';
  testOutput->screen[1][0] = 'B';
  testOutput->screen[1][25] = 'B';
  testOutput->screen[1][40] = 'B';
  testOutput->screen[1][50] = 'B';
  testOutput->screen[2][0] = 'M';
  testOutput->screen[3][0] = 'R';
  testOutput->screen[32][0] = 'R';
  testOutput->outputType = TESTING;
  //testOutput->outputType = ASCII;
  Output(testOutput);
  // strcpy(testOutput->outputFileName,"./testOut.txt");
  // testOutput->outputType = 0;
  // Output(testOutput);
  free_script(testOutput);

  script* testPROG = init_script();
  init_wordArray(testPROG);
  testPROG->outputType = TESTING;
  testPROG->index = 0;
  strcpy(testPROG->wordArray[testPROG->index],"START");
  addWord(testPROG);
  testPROG->index = 1;
  strcpy(testPROG->wordArray[testPROG->index],"END");
  testPROG->index = 0;
  assert(PROG(testPROG) == 1);
  assert(strcmp(testPROG->errorMessage,"") == 0);
  freeWordArray(testPROG);
  free_script(testPROG);
  
  script* testPROG1 = init_script();
  init_wordArray(testPROG1);
  testPROG1->index = 0;
  strcpy(testPROG1->wordArray[testPROG1->index],"END");
  assert(PROG(testPROG1) == 0);
  assert(strcmp(testPROG1->errorMessage,"Error")!=0);
  freeWordArray(testPROG1);
  free_script(testPROG1);

  script* testINSLST = init_script();
  init_wordArray(testINSLST);
  testINSLST->index = 0;
  strcpy(testINSLST->wordArray[testINSLST->index],"END");
  assert(INSLST(testINSLST)==1);
  freeWordArray(testINSLST);
  free_script(testINSLST);

  script* testINSLST1 = init_script();
  init_wordArray(testINSLST1);
  testINSLST1->outputType = TESTING;
  testINSLST1->index = 0;
  strcpy(testINSLST1->wordArray[testINSLST1->index],"FORWARD");
  addWord(testINSLST1);
  testINSLST1->index = 1;
  strcpy(testINSLST1->wordArray[testINSLST1->index],"10");
  addWord(testINSLST1);
  testINSLST1->index = 0;
  assert(INSLST(testINSLST1)==0);
  freeWordArray(testINSLST1);
  free_script(testINSLST1);

  script* testINSLST2 = init_script();
  init_wordArray(testINSLST2);
  testINSLST2->outputType = TESTING;
  testINSLST2->index = 0;
  strcpy(testINSLST2->wordArray[testINSLST2->index],"FORWARD");
  addWord(testINSLST2);
  testINSLST2->index = 1;
  strcpy(testINSLST2->wordArray[testINSLST2->index],"10");
  addWord(testINSLST2);
  testINSLST2->index = 2;
  strcpy(testINSLST2->wordArray[testINSLST2->index],"END");
  addWord(testINSLST2);
  testINSLST2->index = 0;
  assert(INSLST(testINSLST2)==1);
  freeWordArray(testINSLST2);
  free_script(testINSLST2);

  script* testINS = init_script();
  init_wordArray(testINS);
  testINS->outputType = TESTING;
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"FORWARD");
  addWord(testINS);
  testINS->index = 1;
  strcpy(testINS->wordArray[testINS->index],"100");
  addWord(testINS);
  testINS->index = 0;
  assert(INS(testINS)==1);
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"RIGHT");
  addWord(testINS);
  assert(INS(testINS)==1);
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"END");
  addWord(testINS);
  assert(INS(testINS)==0);
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"COLOUR");
  testINS->index = 1;
  strcpy(testINS->wordArray[testINS->index],"\"BLACK\"");
  testINS->index = 0;
  assert(INS(testINS)==1);
  testINS->index = 1;
  strcpy(testINS->wordArray[testINS->index],"$A");
  testINS->index = 0;
  assert(INS(testINS)==0);
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"LOOP");
  testINS->index = 1;
  strcpy(testINS->wordArray[testINS->index],"A");
  addWord(testINS);
  testINS->index = 2;
  strcpy(testINS->wordArray[testINS->index],"OVER");
  addWord(testINS);
  testINS->index = 3;
  strcpy(testINS->wordArray[testINS->index],"{");
  addWord(testINS);
  testINS->index = 4;
  strcpy(testINS->wordArray[testINS->index],"\"BLACK\"");
  addWord(testINS);
  testINS->index = 5;
  strcpy(testINS->wordArray[testINS->index],"}");
  addWord(testINS);
  testINS->index = 6;
  strcpy(testINS->wordArray[testINS->index],"END");
  testINS->index = 0;
  assert(INS(testINS)==1);
  testINS->index = 0;
  strcpy(testINS->wordArray[testINS->index],"SET");  
  testINS->index = 1;
  strcpy(testINS->wordArray[testINS->index],"A");
  testINS->index = 2;
  strcpy(testINS->wordArray[testINS->index],"(");
  testINS->index = 3;
  strcpy(testINS->wordArray[testINS->index],"1");
  testINS->index = 4;
  strcpy(testINS->wordArray[testINS->index],"+");
  testINS->index = 5;
  strcpy(testINS->wordArray[testINS->index],"1");
  testINS->index = 5;
  strcpy(testINS->wordArray[testINS->index],")");
  testINS->index = 0;
  assert(INS(testINS)==1);
  freeWordArray(testINS);
  free_script(testINS);

  //need to edit to include vars
  script* testFWD = init_script();
  init_wordArray(testFWD);
  init_VARArray(testFWD);
  testFWD->index = 0;
  testFWD->outputType = TESTING;
  strcpy(testFWD->wordArray[testFWD->index],"FORWARD");
  addWord(testFWD);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"10");
  addWord(testFWD);
  testFWD->index = 0;
  assert(FWD(testFWD)==1); 
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"1");
  testFWD->index = 0;
  assert(FWD(testFWD)==1); 
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"-10");
  testFWD->index = 0;
  assert(FWD(testFWD)==1);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"-1");
  testFWD->index = 0;
  assert(FWD(testFWD)==1);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"$A");
  testFWD->index = 0;
  assert(FWD(testFWD)==0); 
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"$B");
  testFWD->index = 0;
  assert(FWD(testFWD)==0); 
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"$AA");
  testFWD->index = 0;
  assert(FWD(testFWD)==0); 
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"$a");
  testFWD->index = 0;
  assert(FWD(testFWD)==0);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"A");
  testFWD->index = 0;
  assert(FWD(testFWD)==0);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"a");
  testFWD->index = 0;
  assert(FWD(testFWD)==0);
  testFWD->index = 1;
  strcpy(testFWD->wordArray[testFWD->index],"$1");
  testFWD->index = 0;
  assert(FWD(testFWD)==0);
  strcpy(testFWD->wordArray[testFWD->index],"RIGHT");
  addWord(testFWD);
  assert(FWD(testFWD)==0);
  strcpy(testFWD->wordArray[testFWD->index],"END");
  addWord(testFWD);
  assert(FWD(testFWD)==0);
  freeWordArray(testFWD);
  free_script(testFWD);

  script* testFWD_Interp = init_script();
  init_wordArray(testFWD_Interp);
  init_turtle(testFWD_Interp);
  testFWD_Interp->outputType = TESTING;
  init_VARArray(testFWD_Interp);
  strcpy(testFWD_Interp->wordArray[0],"FORWARD");  
  addWord(testFWD_Interp);
  testFWD_Interp->index = 1;
  strcpy(testFWD_Interp->wordArray[1],"5");
  testFWD_Interp->index = 0;
  addWord(testFWD_Interp);
  testFWD_Interp->outputType = TESTING;
  FWD(testFWD_Interp);
  assert(testFWD_Interp->screen[15][25] == 'W');
  assert(testFWD_Interp->screen[11][25] == 'W');
  int indexFWD = LTRToVarArrayIndex('A');
  testFWD_Interp->VARArray[indexFWD].VARType = NUMBER;
  testFWD_Interp->VARArray[indexFWD].NUMBER = 10;
  testFWD_Interp->turtle_Degrees = 0;
  testFWD_Interp->index = 1;
  strcpy(testFWD_Interp->wordArray[1],"$A");
  testFWD_Interp->index = 0;
  FWD(testFWD_Interp);  
  assert(testFWD_Interp->screen[15][25] == 'W');
  assert(testFWD_Interp->screen[11][25] == 'W');
  freeWordArray(testFWD_Interp);
  free_script(testFWD_Interp);

  //need to edit to inclued numbers
  script* testRGT = init_script();
  init_wordArray(testRGT);
  init_VARArray(testRGT);
  testRGT->outputType = TESTING;
  testRGT->index = 0;
  strcpy(testRGT->wordArray[testRGT->index],"RIGHT");
  addWord(testRGT);
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"10");
  addWord(testRGT);
  testRGT->index = 0;
  assert(RGT(testRGT)==1); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"1");
  testRGT->index = 0;
  assert(RGT(testRGT)==1); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"$A");
  testRGT->index = 0;
  testRGT->VARArray[0].VARType = NUMBER;
  assert(RGT(testRGT)==1); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"$AA");
  testRGT->index = 0;
  assert(RGT(testRGT)==0); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"$a");
  testRGT->index = 0;
  assert(RGT(testRGT)==0); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"a");
  testRGT->index = 0;
  assert(RGT(testRGT)==0); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"A");
  testRGT->index = 0;
  assert(RGT(testRGT)==0); 
  testRGT->index = 1;
  strcpy(testRGT->wordArray[testRGT->index],"$1");
  testRGT->index = 0;
  assert(RGT(testRGT)==0); 
  strcpy(testRGT->wordArray[testRGT->index],"LEFT");
  addWord(testRGT);
  assert(RGT(testRGT)==0);
  strcpy(testRGT->wordArray[testRGT->index],"END");
  addWord(testRGT);
  assert(RGT(testRGT)==0);
  freeWordArray(testRGT);
  free_script(testRGT);

  script* testRGT_Interp = init_script();
  init_wordArray(testRGT_Interp);
  init_turtle(testRGT_Interp);
  testRGT_Interp->outputType = TESTING; 
  //num
  strcpy(testRGT_Interp->wordArray[0],"RIGHT");  
  addWord(testRGT_Interp);
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"90");
  testRGT_Interp->index = 0;
  addWord(testRGT_Interp);
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 90);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"180");
  testRGT_Interp->index = 0;
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 180);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"270");
  testRGT_Interp->index = 0;
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 270);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"360");
  testRGT_Interp->index = 0;
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 360);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"370");
  testRGT_Interp->index = 0;  
  RGT(testRGT_Interp);
  assert(testRGT_Interp->turtle_Degrees == 10);
  init_VARArray(testRGT_Interp);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"$A");
  testRGT_Interp->index = 0;
  int index = LTRToVarArrayIndex('A');
  testRGT_Interp->VARArray[index].VARType = NUMBER;
  testRGT_Interp->VARArray[index].NUMBER = 10;
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 10);
  testRGT_Interp->turtle_Degrees = 0;
  testRGT_Interp->index = 1;
  strcpy(testRGT_Interp->wordArray[1],"$A");
  testRGT_Interp->index = 0;
  index = LTRToVarArrayIndex('A');
  testRGT_Interp->VARArray[index].VARType = WORDCOLOUR;
  strcpy(testRGT_Interp->VARArray[index].WORDCOLOUR, "\"RED\"");
  RGT(testRGT_Interp);  
  assert(testRGT_Interp->turtle_Degrees == 10);
  freeWordArray(testRGT_Interp);
  free_script(testRGT_Interp);

  script* testCOL = init_script();
  init_wordArray(testCOL);
  testCOL->index = 0;
  strcpy(testCOL->wordArray[testCOL->index],"COLOUR");
  addWord(testCOL);
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"$A");
  addWord(testCOL);
  // addWord(testCOL);
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"\"RED\"");
  testCOL->index = 0;
  assert(COL(testCOL)==1);   
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"\"BLACK\"");
  testCOL->index = 0;
  assert(COL(testCOL)==1); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"$B");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"$AA");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"$a");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"a");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"A");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  testCOL->index = 1;
  strcpy(testCOL->wordArray[testCOL->index],"$1");
  testCOL->index = 0;
  assert(COL(testCOL)==0); 
  strcpy(testCOL->wordArray[testCOL->index],"LEFT");
  addWord(testCOL);
  assert(COL(testCOL)==0);
  strcpy(testCOL->wordArray[testCOL->index],"END");
  addWord(testCOL);
  assert(COL(testCOL)==0);
  strcpy(testCOL->wordArray[testCOL->index],"red");
  addWord(testCOL);
  assert(COL(testCOL)==0);
  strcpy(testCOL->wordArray[testCOL->index],"red red");
  addWord(testCOL);
  assert(COL(testCOL)==0);
  strcpy(testCOL->wordArray[testCOL->index],"red red red");
  addWord(testCOL);
  assert(COL(testCOL)==0);
  freeWordArray(testCOL);
  free_script(testCOL);

  script* testCOLInterpVars = init_script();
  init_wordArray(testCOLInterpVars);
  init_VARArray(testCOLInterpVars);
  testCOLInterpVars->outputType = TESTING; 
  testCOLInterpVars->VARArray[0].VARType = WORDCOLOUR;
  strcpy(testCOLInterpVars->VARArray[0].WORDCOLOUR, "\"BLACK\"");
  strcpy(testCOLInterpVars->wordArray[0],"$A");
  testCOLInterpVars->index = 0;
  COL_Interp_Vars(testCOLInterpVars);
  assert(testCOLInterpVars->turtle_Colour == 'K');
  freeWordArray(testCOLInterpVars);
  free_script(testCOLInterpVars);

  char testColourToChar[50] = "\"BLACK\"";
  assert(colourToChar(testColourToChar) == 'K');
  strcpy(testColourToChar,"\"RED\"");
  assert(colourToChar(testColourToChar) == 'R');
  strcpy(testColourToChar,"\"GREEN\"");
  assert(colourToChar(testColourToChar) == 'G');
  strcpy(testColourToChar,"\"BLUE\"");
  assert(colourToChar(testColourToChar) == 'B');
  strcpy(testColourToChar,"\"YELLOW\"");
  assert(colourToChar(testColourToChar) == 'Y');
  strcpy(testColourToChar,"\"CYAN\"");
  assert(colourToChar(testColourToChar) == 'C');
  strcpy(testColourToChar,"\"MAGENTA\"");
  assert(colourToChar(testColourToChar) == 'M');
  strcpy(testColourToChar,"\"WHITE\"");
  assert(colourToChar(testColourToChar) == 'W');
  strcpy(testColourToChar,"\"TEST\"");
  assert(colourToChar(testColourToChar) == 'E');

  script* testisVARCOLOUR = init_script();
  init_wordArray(testisVARCOLOUR);
  int indextestisVARCOLOUR = testisVARCOLOUR->index;
  strcpy(testisVARCOLOUR->wordArray[0],"\"BLACK\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"RED\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"GREEN\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"BLUE\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"YELLOW\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"CYAN\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"MAGENTA\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"WHITE\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == true);
  strcpy(testisVARCOLOUR->wordArray[0],"\"TEST\"");
  assert(isVARCOLOUR(testisVARCOLOUR,indextestisVARCOLOUR) == false);
  freeWordArray(testisVARCOLOUR);
  free_script(testisVARCOLOUR);

  script* testCOL_Interp = init_script();
  init_wordArray(testCOL_Interp);
  init_turtle(testCOL_Interp);
  testCOL_Interp->outputType = TESTING;
  //WORD
  strcpy(testCOL_Interp->wordArray[0],"COLOUR");  
  addWord(testCOL_Interp);
  testCOL_Interp->index = 1;
  strcpy(testCOL_Interp->wordArray[1],"\"RED\"");
  testCOL_Interp->index = 0;
  addWord(testCOL_Interp);
  COL(testCOL_Interp);  
  assert(testCOL_Interp->turtle_Colour == 'R');
  testCOL_Interp->index = 1;
  strcpy(testCOL_Interp->wordArray[1],"\"WHITE\"");
  testCOL_Interp->index = 0;
  COL(testCOL_Interp); 
  assert(testCOL_Interp->turtle_Colour == 'W');
  testCOL_Interp->index = 1;
  strcpy(testCOL_Interp->wordArray[1],"\"GREEN\"");
  testCOL_Interp->index = 0;
  COL(testCOL_Interp); 
  assert(testCOL_Interp->turtle_Colour == 'G');
  freeWordArray(testCOL_Interp);
  free_script(testCOL_Interp);

  script* testCOL_Interp_Vars = init_script();
  init_wordArray(testCOL_Interp_Vars);
  init_turtle(testCOL_Interp_Vars);
  testCOL_Interp_Vars->outputType = TESTING;
  init_VARArray(testCOL_Interp_Vars);
  int indexOne = LTRToVarArrayIndex('A');
  testCOL_Interp_Vars->VARArray[indexOne].VARType = WORDCOLOUR;
  strcpy(testCOL_Interp_Vars->VARArray[indexOne].WORDCOLOUR,"\"RED\"");
  //WORD
  strcpy(testCOL_Interp_Vars->wordArray[0],"COLOUR");  
  addWord(testCOL_Interp_Vars);
  testCOL_Interp_Vars->index = 1;
  strcpy(testCOL_Interp_Vars->wordArray[1],"$A");
  testCOL_Interp_Vars->index = 0;
  addWord(testCOL_Interp_Vars);
  COL(testCOL_Interp_Vars);  
  assert(testCOL_Interp_Vars->turtle_Colour == 'R');
  freeWordArray(testCOL_Interp_Vars);
  free_script(testCOL_Interp_Vars);

  script* testLOOP = init_script();
  init_wordArray(testLOOP);
  strcpy(testLOOP->wordArray[testLOOP->index],"LOOP");
  addWord(testLOOP);
  testLOOP->index = 1;
  strcpy(testLOOP->wordArray[testLOOP->index],"A");
  addWord(testLOOP);
  testLOOP->index = 2;
  strcpy(testLOOP->wordArray[testLOOP->index],"OVER");
  addWord(testLOOP);
  testLOOP->index = 3;
  strcpy(testLOOP->wordArray[testLOOP->index],"{");
  addWord(testLOOP);
  testLOOP->index = 4;
  strcpy(testLOOP->wordArray[testLOOP->index],"\"RED\"");
  addWord(testLOOP);
  testLOOP->index = 5;
  strcpy(testLOOP->wordArray[testLOOP->index],"}");
  addWord(testLOOP);
  testLOOP->index = 6;
  strcpy(testLOOP->wordArray[testLOOP->index],"END");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==1); 
  testLOOP->index = 4;
  strcpy(testLOOP->wordArray[testLOOP->index],"10");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==1);
  testLOOP->index = 0;
  strcpy(testLOOP->wordArray[testLOOP->index],"SET");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 0;
  strcpy(testLOOP->wordArray[testLOOP->index],"LOOP");
  testLOOP->index = 1;
  strcpy(testLOOP->wordArray[testLOOP->index],"$A");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 1;
  strcpy(testLOOP->wordArray[testLOOP->index],"A");
  testLOOP->index = 2;
  strcpy(testLOOP->wordArray[testLOOP->index],"TEST");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 2;
  strcpy(testLOOP->wordArray[testLOOP->index],"OVER");
  testLOOP->index = 3;
  strcpy(testLOOP->wordArray[testLOOP->index],"}");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 3;
  strcpy(testLOOP->wordArray[testLOOP->index],"{");
  testLOOP->index = 4;
  strcpy(testLOOP->wordArray[testLOOP->index],"red red");
  testLOOP->index = 0;
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 4;
  strcpy(testLOOP->wordArray[testLOOP->index],"RED");
  testLOOP->index = 5;
  strcpy(testLOOP->wordArray[testLOOP->index],"{");
  assert(LOOP(testLOOP)==0);
  testLOOP->index = 5;
  strcpy(testLOOP->wordArray[testLOOP->index],"}");
  freeWordArray(testLOOP);
  free_script(testLOOP);

  script* testLoopInterp = init_script();
  init_wordArray(testLoopInterp);
  init_turtle(testLoopInterp);
  testLoopInterp->outputType = TESTING;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"LOOP");
  addWord(testLoopInterp);
  testLoopInterp->index = 1;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"A");
  addWord(testLoopInterp);
  testLoopInterp->index = 2;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"OVER");
  addWord(testLoopInterp);
  testLoopInterp->index = 3;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"{");
  addWord(testLoopInterp);
  testLoopInterp->index = 4;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"10");
  addWord(testLoopInterp);
  testLoopInterp->index = 5;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"}");
  addWord(testLoopInterp);
  testLoopInterp->index = 6;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"FORWARD");
  addWord(testLoopInterp);
  testLoopInterp->index = 7;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"10");
  addWord(testLoopInterp);
  testLoopInterp->index = 8;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"END");
  addWord(testLoopInterp);
  testLoopInterp->index = 0;
  LOOP(testLoopInterp);
  assert((int)testLoopInterp->VARArray->NUMBER == 10);
  testLoopInterp->index = 4;
  strcpy(testLoopInterp->wordArray[testLoopInterp->index],"\"RED\"");
  testLoopInterp->index = 0;
  LOOP(testLoopInterp);
  assert(strcmp(testLoopInterp->VARArray[0].WORDCOLOUR,"\"RED\"") == 0);
  freeWordArray(testLoopInterp);
  free_script(testLoopInterp);

  script* testIndexStartLoop = init_script();
  init_wordArray(testIndexStartLoop);
  init_turtle(testIndexStartLoop);
  testIndexStartLoop->outputType = TESTING;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"LOOP");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 1;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"A");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 2;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"OVER");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 3;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"{");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 4;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"\"RED\"");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 5;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"}");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 6;
  strcpy(testIndexStartLoop->wordArray[testIndexStartLoop->index],"END");
  addWord(testIndexStartLoop);
  testIndexStartLoop->index = 0;
  LOOP(testIndexStartLoop);
  int result = indexStartLoop(testIndexStartLoop);
  assert(result == 0);
  freeWordArray(testIndexStartLoop);
  free_script(testIndexStartLoop);
 
  script* testSET = init_script();
  init_wordArray(testSET);
  strcpy(testSET->wordArray[testSET->index],"SET");
  addWord(testSET);
  testSET->index = 1;
  strcpy(testSET->wordArray[testSET->index],"A");
  addWord(testSET);
  testSET->index = 2;
  strcpy(testSET->wordArray[testSET->index],"(");
  addWord(testSET);
  testSET->index = 3;
  strcpy(testSET->wordArray[testSET->index],"1");
  addWord(testSET);
  testSET->index = 4;
  strcpy(testSET->wordArray[testSET->index],"1");
  addWord(testSET);
  testSET->index = 5;
  strcpy(testSET->wordArray[testSET->index],"+");
  addWord(testSET);
  testSET->index = 6;
  strcpy(testSET->wordArray[testSET->index],")");
  testSET->index = 0;
  assert(SET(testSET)==1);
  assert(testSET->VARArray[0].VARType == NUMBER);
  assert((int)testSET->VARArray[0].NUMBER == 2);
  testSET->index = 0;
  strcpy(testSET->wordArray[testSET->index],"TEST");
  testSET->index = 0;
  assert(SET(testSET)==0);
  strcpy(testSET->wordArray[testSET->index],"SET");
  testSET->index = 1;
  strcpy(testSET->wordArray[testSET->index],"$A");
  testSET->index = 0;
  assert(SET(testSET)==0);
  testSET->index = 1;
  strcpy(testSET->wordArray[testSET->index],"A");
  testSET->index = 2;
  strcpy(testSET->wordArray[testSET->index],")");
  testSET->index = 0;
  assert(SET(testSET)==0);
  testSET->index = 2;
  strcpy(testSET->wordArray[testSET->index],"(");
  testSET->index = 3;
  strcpy(testSET->wordArray[testSET->index],"(");
  testSET->index = 0;
  assert(SET(testSET)==0);
  testSET->index = 3;
  strcpy(testSET->wordArray[testSET->index],"1");
  freeWordArray(testSET);
  free_script(testSET);

  script* testVARNUM = init_script();
  init_wordArray(testVARNUM);
  init_VARArray(testVARNUM);
  testVARNUM->VARArray[0].VARType = NUMBER;
  strcpy(testVARNUM->wordArray[testVARNUM->index],"$A");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"0");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"1");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"5");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"-1");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"-10");
  assert(VARNUM(testVARNUM)==1);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"$AA");
  assert(VARNUM(testVARNUM)==0);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"$a");
  assert(VARNUM(testVARNUM)==0);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"$aa");
  assert(VARNUM(testVARNUM)==0);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"AA");
  assert(VARNUM(testVARNUM)==0);
  strcpy(testVARNUM->wordArray[testVARNUM->index],"aa");
  assert(VARNUM(testVARNUM)==0);
  freeWordArray(testVARNUM);
  free_script(testVARNUM);

  
  script* testLTR = init_script();
  init_wordArray(testLTR);
  int LTRindex = testLTR->index;
  strcpy(testLTR->wordArray[testLTR->index],"A");
  assert(LTR(testLTR,&LTRindex)==1);
  strcpy(testLTR->wordArray[testLTR->index],"a");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->wordArray[testLTR->index],"aa");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->wordArray[testLTR->index],"AA");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->wordArray[testLTR->index],"B");
  assert(LTR(testLTR,&LTRindex)==1);
  strcpy(testLTR->wordArray[testLTR->index],"b");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->wordArray[testLTR->index],"bb");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->wordArray[testLTR->index],"BB");
  assert(LTR(testLTR,&LTRindex)==0);
  strcpy(testLTR->prevInstruction,"VAR");
  strcpy(testLTR->wordArray[testLTR->index],"$A");
  testLTR->VARArray[0].VARType = WORDCOLOUR;
  assert(LTR(testLTR,&LTRindex)==1);
  assert(strcmp(testLTR->prevInstruction,"") == 0);
  testLTR->VARArray[1].VARType = WORDCOLOUR;
  strcpy(testLTR->prevInstruction,"VAR");
  strcpy(testLTR->wordArray[testLTR->index],"$B");
  assert(LTR(testLTR,&LTRindex)==1);
  assert(strcmp(testLTR->prevInstruction,"") == 0);
  freeWordArray(testLTR);
  free_script(testLTR);

  script* testVAR = init_script();
  init_wordArray(testVAR);
  init_VARArray(testVAR);
  testVAR->index = 0;
  strcpy(testVAR->wordArray[testVAR->index],"$A");
  testVAR->VARArray[0].VARType = WORDCOLOUR;
  assert(VAR(testVAR)==1);
  strcpy(testVAR->wordArray[testVAR->index],"$B");
  testVAR->VARArray[1].VARType = WORDCOLOUR;
  assert(VAR(testVAR)==1);
  strcpy(testVAR->wordArray[testVAR->index],"$C");
  testVAR->VARArray[2].VARType = WORDCOLOUR;
  assert(VAR(testVAR)==1);
  strcpy(testVAR->wordArray[testVAR->index],"$AA");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$BB");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$CC");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$a");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$b");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$c");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$aa");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$bb");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"$cc");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"a");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"aa");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"b");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"bb");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"c");
  assert(VAR(testVAR)==0);
  strcpy(testVAR->wordArray[testVAR->index],"cc");
  assert(VAR(testVAR)==0);
  freeWordArray(testVAR);
  free_script(testVAR);

  script* testVarArray = init_script();
  init_VARArray(testVarArray);
  testVarArray->VARArray[0].VARType = WORDCOLOUR;
  strcpy(testVarArray->VARArray[0].WORDCOLOUR,"\"RED\"");
  assert(strcmp(testVarArray->VARArray[0].WORDCOLOUR,"\"RED\"") == 0);
  testVarArray->VARArray[0].VARType = NUMBER;
  testVarArray->VARArray[0].NUMBER = 10;
  assert((int)testVarArray->VARArray[0].NUMBER == 10);
  testVarArray->VARArray[25].VARType = WORDCOLOUR;
  strcpy(testVarArray->VARArray[0].WORDCOLOUR,"\"RED\"");
  assert(strcmp(testVarArray->VARArray[0].WORDCOLOUR,"\"RED\"") == 0);
  testVarArray->VARArray[25].VARType = NUMBER;
  testVarArray->VARArray[25].NUMBER = 10;
  assert((int)testVarArray->VARArray[0].NUMBER == 10);
  free_script(testVarArray);

  char letter = 'A';
  assert(LTRToVarArrayIndex(letter) == 0);
  letter = 'B';
  assert(LTRToVarArrayIndex(letter) == 1);
  letter = 'Z';
  assert(LTRToVarArrayIndex(letter) == 25);


  script* testNUM = init_script();
  init_wordArray(testNUM);
  strcpy(testNUM->wordArray[testNUM->index],"10");
  addWord(testNUM);
  assert(NUM(testNUM)==1);
  strcpy(testNUM->wordArray[testNUM->index],"1");
  assert(NUM(testNUM)==1);
  strcpy(testNUM->wordArray[testNUM->index],"0");
  assert(NUM(testNUM)==1);
  strcpy(testNUM->wordArray[testNUM->index],"-1");
  assert(NUM(testNUM)==1);
  strcpy(testNUM->wordArray[testNUM->index],"START");
  assert(NUM(testNUM)==0);
  strcpy(testNUM->wordArray[testNUM->index],"END");
  assert(NUM(testNUM)==0);
  freeWordArray(testNUM);
  free_script(testNUM);

  script* testWORD = init_script();
  init_wordArray(testWORD);
  strcpy(testWORD->wordArray[testWORD->index],"\"BLACK\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"RED\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"GREEN\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"BLUE\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"YELLOW\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"CYAN\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"MAGENTA\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"WHITE\"");
  assert(WORD(testWORD)==1);
  strcpy(testWORD->wordArray[testWORD->index],"\"WHITE\" \"WHITE\"");
  assert(WORD(testWORD)==0);
  strcpy(testWORD->wordArray[testWORD->index],"\"white \" \"white\"");
  assert(WORD(testWORD)==0);
  strcpy(testWORD->wordArray[testWORD->index],"\"RED\" \"RED\" \"RED\"");
  assert(WORD(testWORD)==0);
  strcpy(testWORD->wordArray[testWORD->index],"\"red\" \"red\" \"red\"");
  assert(WORD(testWORD)==0);
  freeWordArray(testWORD);
  free_script(testWORD);

  script* testLST = init_script();
  init_wordArray(testLST);
  init_VARArray(testLST);

  int LSTindex = testLST->index;
  strcpy(testLST->wordArray[testLST->index],"{");
  addWord(testLST);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"\"RED\"");
  addWord(testLST);
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"}");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1); 
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"1");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"-1");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1);
  testLST->index = 1;
  testLST->VARArray[0].VARType = WORDCOLOUR;
  strcpy(testLST->wordArray[testLST->index],"$A");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"$AA");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"$a");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"\"BLACK\" \"BLACK\"");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 0;
  strcpy(testLST->wordArray[testLST->index],"}");
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"\"BLACK\"");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 0;
  strcpy(testLST->wordArray[testLST->index],"{");
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"\"RED\"");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"\"RED\"");
  addWord(testLST);
  testLST->index = 3;
  strcpy(testLST->wordArray[testLST->index],"}");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1); 
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"10");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"10");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==1);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"$A");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"$B");
  testLST->index = 0;
  testLST->VARArray[1].VARType = WORDCOLOUR;
  assert(LST(testLST,&LSTindex)==1);
  testLST->index = 0;
  strcpy(testLST->wordArray[testLST->index],"}");
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"$A");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"$B");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"$AA");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"$A");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  testLST->index = 1;
  strcpy(testLST->wordArray[testLST->index],"\"BLACK\" \"BLACK\"");
  testLST->index = 2;
  strcpy(testLST->wordArray[testLST->index],"$A");
  testLST->index = 0;
  assert(LST(testLST,&LSTindex)==0);
  freeWordArray(testLST);
  free_script(testLST);

  script* testITEMS = init_script();
  init_wordArray(testITEMS);
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==1);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"\"RED\"");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==1);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"$A");
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  testITEMS->VARArray[0].VARType = WORDCOLOUR;
  assert(ITEMS(testITEMS)==1);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"1");
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==1);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"-1");
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==1);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"{");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"\"RED\" \"RED\"");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"\"RANDOM\"");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"\"red\" \"red\"");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"$AA");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"$a");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  testITEMS->index = 0;
  strcpy(testITEMS->wordArray[testITEMS->index],"$AA");
  addWord(testITEMS);
  testITEMS->index = 1;
  strcpy(testITEMS->wordArray[testITEMS->index],"}");
  testITEMS->index = 0;
  assert(ITEMS(testITEMS)==0);
  freeWordArray(testITEMS);
  free_script(testITEMS);

  script* testITEM = init_script();
  init_wordArray(testITEM);
  init_VARArray(testITEM);
  testITEM->VARArray[0].VARType = NUMBER;
  strcpy(testITEM->wordArray[testITEM->index],"$A");
  assert(ITEM(testITEM)==1);
  strcpy(testITEM->wordArray[testITEM->index],"1");
  assert(ITEM(testITEM)==1);
  strcpy(testITEM->wordArray[testITEM->index],"-1");
  assert(ITEM(testITEM)==1);
  strcpy(testITEM->wordArray[testITEM->index],"\"BLACK\"");
  assert(ITEM(testITEM)==1);
  strcpy(testITEM->wordArray[testITEM->index],"$AA");
  assert(ITEM(testITEM)==0);
  strcpy(testITEM->wordArray[testITEM->index],"$a");
  assert(ITEM(testITEM)==0);
  strcpy(testITEM->wordArray[testITEM->index],"$aa");
  assert(ITEM(testITEM)==0);
  strcpy(testITEM->wordArray[testITEM->index],"\"black\"");
  assert(ITEM(testITEM)==0);
  strcpy(testITEM->wordArray[testITEM->index],"\"BLACK\" \"BLACK\"");
  assert(ITEM(testITEM)==0);
  strcpy(testITEM->wordArray[testITEM->index],"\"black\" \"black\"");
  assert(ITEM(testITEM)==0);
  freeWordArray(testITEM);
  free_script(testITEM);

  script* testPFIX = init_script();
  init_wordArray(testPFIX);
  init_VARArray(testPFIX);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"SET");
  addWord(testPFIX);
  testPFIX->index = 1;
  strcpy(testPFIX->wordArray[testPFIX->index],"A");
  addWord(testPFIX);
  testPFIX->index = 2;
  strcpy(testPFIX->wordArray[testPFIX->index],"(");
  addWord(testPFIX);
  testPFIX->index = 3;
  strcpy(testPFIX->wordArray[testPFIX->index],"1");
  addWord(testPFIX);
  testPFIX->index = 4;
  strcpy(testPFIX->wordArray[testPFIX->index],"1");
  addWord(testPFIX);
  testPFIX->index = 5;
  strcpy(testPFIX->wordArray[testPFIX->index],"+");
  addWord(testPFIX);
  testPFIX->index = 6;
  strcpy(testPFIX->wordArray[testPFIX->index],")");
  int LTRplaceholder = 1;
  testPFIX->index = 3;
  assert(PFIX(testPFIX,LTRplaceholder)==1);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"(");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],")");
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"\\");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"$a");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"$AA");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"a");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  testPFIX->index = 0;
  strcpy(testPFIX->wordArray[testPFIX->index],"aa");
  assert(PFIX(testPFIX,LTRplaceholder)==0);
  freeWordArray(testPFIX);
  free_script(testPFIX);

  script* testOP = init_script();
  init_wordArray(testOP);
  strcpy(testOP->wordArray[testOP->index],"+");
  assert(OP(testOP)==1);
  strcpy(testOP->wordArray[testOP->index],"-");
  assert(OP(testOP)==1);
  strcpy(testOP->wordArray[testOP->index],"/");
  assert(OP(testOP)==1);
  strcpy(testOP->wordArray[testOP->index],"*");
  assert(OP(testOP)==1);
  strcpy(testOP->wordArray[testOP->index],"x");
  assert(OP(testOP)==0);
  strcpy(testOP->wordArray[testOP->index],"+=");
  assert(OP(testOP)==0);
  freeWordArray(testOP);
  free_script(testOP);



}




